# A Reflection On The Past Three Years

Written on August 13th in the year 2018.

---

Almost three years ago, my wife and I moved from Wheaton to Pasadena, California. At the time I was just coming out of a three and a half year stretch of doing professional photography, and I was burnt out. It isn't easy to navigate the feelings of confusion you get when you realize you are sick and tired of doing the thing you thought you were meant to be doing.

Initially when we moved out, it was for my wife to pursue graduate school in the field of psychology. Truth be told I had no idea what I was going to do next. I had taken a couple web design courses in high school, and I had some friends from college that had gotten into web development, so I thought to myself "why not give this a try."

Fast-forward three years, and I feel like I'm only just beginning to realize how far down the rabbit trail goes. I spent the first 6 months of being in California studying web development 80 hours a week. I learned everything from the basics of html and css to building out full stack applications using node, angular, and a plethora of other technologies (many of which are probably no longer relevant #techmovesfastbro). In the spring of 2016, I started a job as a full-stack engineer working for a startup in Santa Monica. We worked predominantly with PHP, which really isn't as bad as people love to say it is. Anyway, it didn't take me long to realize that I was in over my head for a number of reasons, one of the main ones being that I was the only engineer onsite. I realized that if I wanted to continue building this skillset, I needed the dynamic that only a team of engineers working together could provide. So I quit.

A couple months later, I started as a junior software engineer at my current company. It's crazy to think that I've been here for two years already, time has flown by. It's so easy in the moment to get discouraged when faced with what seems like a impossible task you're not certain how to finish. Panic sets in, imposter syndrome rents a room in your mind and you begin to wonder if building that very first "hello world" application was the right choice or a very bad mistake. To be honest, I feel like this most days still. That is partially why I've written this post, just as a simple reminder to myself and whoever somehow stumbles upon it. I once heard that the only person I should compare myself to is the man I was two years ago. There was a time when if you had asked me to spin up some docker containers, link them together, and run some microservices on them I would have looked at you wide eyed and said "excuse me?". Or, there was a time when if you had asked me to deploy some changes to the code base of a wordpress repository I probably would have deleted the folder system itself (I actually did do this, but that's for another time). My point is that I've realized that being in the industry of software development is truly a marathon. Things take time, things change a lot, pace is of the utmost importance. Pace and patience. All of the things I mentioned above, I know how to do now, and more.

So anyway, that's a little bit about what's been going on in the past few years of my life. This is my blog, where I'll occasionally write about things related to web development, or things unrelated. Thanks for reading!
